language: node_js

node_js:
  - node

cache: npm

install:
  - npm install

script:
  - npm run test:unit

after_success:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

env:
  global:
    secure: JTs5f6TObN5Pt149dgnRP2TQ4xCcTXotZGZ8IOVKcHkH3VZ0dXwK0GDCHLSiLTB+BTjj7F+73H2UyZVhiDvHw/XOE4TQiak53+ByJmqkQYvhDJZYp9C579DIeqHDdrUM8rEi0ZSKR+bLRjpJ7clZwdbe/5CIaXcTFtd4PbDocJwhmHdFvYaEY1W+XYRgMaxvlg9dXz5LHtV7+LnY0Ej0Am9t/trKnKhNn/59KWHiMA+8RNPi0rcndk6HMi7z7BifFNvmcyiJT8YPP4j+VpHBGf+ppe5kbpoVBot1tedCzRQUkLaJj2GAwmCWFxrkYHKDd/F6c5ICfRkYhkVA0SzU3gh6VjzfOqthbTVYRU1E114kymmv4wqCrlI8TdQrQahPJweMtuocstcqTQzOup/aBfwolhXKDuDNqXQjIqUcQpAAOv39GuAI8whKXHA8a3l61Qh3Qan7Q7FVZ8NReoWANBJrQthC0O5EotPpdVkZFhKck08jZ1tp3/444vEDC1Fsb49896d1TRhIOwJedvqMn4fkhZ6Ao+WZjd22bXbL7QW4VQc030mm5VbQSL+SSTOIPZUurYflOKPhGcfTwwCSTI/5N4md+jYEuYT8RD8Aw9eLVYuMUK2wHyHa8uxK2fWMRzyB4HVJVCjRN7oImbN7iaviQVaVHEZ+bWyB/31cnTE=
