language: node_js

os: linux
dist: xenial

node_js:
  - lts/*

cache: npm

install:
  - npm install

script:
  - npm run lint
  - npm run test:unit

after_success:
  - npm run build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN

  cleanup: true
  local_dir: dist

  repo: dhruvkb/dhruvkb.github.io
  target_branch: master
  committer_from_gh: true
  on:
    branch: master
